language: node_js
node_js:
- 6
- 7
- 8
- 9
- 11
- lts/*
- node
before_script:
- npm i codecov nyc --save-dev
script:
- npm run lint
- npm run coverageTest
after_success: npm run coverage
deploy:
  provider: npm
  email: lkloon123@hotmail.com
  api_key:
    secure: YsZSwXaBwgAZb8Ra+Sd4bd7WFEsbwaQhWUuSkwlLH6ShR/61iR1oGORvldPpj35Qc/g2K0YEBPoxkU/v8PXBI5aodvIIMDfuIdvrYfrKbkTawI3VoDgg0i1j5eB34gq+7L3BI0Qg4J85qlIQYDSOJLWm8zTvz3nFPPw1jtGax6pF4G0/DMfuYDq+PjeYINKGUFBYGbVDfO+dZ45sg7sr85N9SfFB4fEZkem98xsfG7XiDqiQ0QJt32O7ZtdqtafvXD5ji9VHvf3fD6cyPYQ8nOoKILWqfwMYP5ZdV7lh6s0gVv8UJaBPVvUByVGlfHYq0+sDjge68hCZcGjp/3STbP6v2FnPMHd0RF2Sd3s29X2J0RHGgJIsNP0nnllG4hKhDLgI85F4wczeceCmTNN+wEsfzL1FJYKdvS0NUToJReXUg53tSxac9t96PfXYgNLDNwBQaLASTPs18Kbw6opPYwDh/xl0y5PrM036sMLdHfW7g2sTQuvV2uXqbDtynNn8JnIB8A5i3FRBOPVu6OGx20vQF8lHxvOvsNDZN/0JXNIvHepIuDdjXZ1Vh2JYnjIGBLd+tTRufRj49swodCbhKXD/4jHQBqj/tRB5wSGiFMrs//rhpI1rGTWr0my19BdDye37mJMiV6Hs5yQl5Mul9mbynTiVm90vMoyX0XP1N18=
  on:
    tags: true
    node: node
  skip_cleanup: true
